pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/SebaTapiaG/kartingTapia']])
                dir("front-end"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("front-end"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t sebatapiag/frontend-image ."
                            bat "docker push sebatapiag/frontend-image ."
                        }
                    }                    
                }
            }
        }
    }
}