pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/SebaTapiaG/kartingTapia']])
                dir("front-end"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("front-end"){
                  script {
                         withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                    bat """
                        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
                    """
                }

                // Construir y empujar la imagen
                bat "docker build -t sebatapiag/frontend-image ."
                bat "docker push sebatapiag/frontend-image"
                }                   
                }
            }
        }
    }
}